### ISSUE TITLE
Add more fancy templates

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/cards#228]
### thebootstrappedfounder

https://twitter.com/joshpitzalis/status/1465673218702909446

![-GNjtxHT](https://user-images.githubusercontent.com/2096101/145730880-e0f72187-d7cc-4e0b-9e09-160511c59682.png)

### apple

https://twitter.com/jlacort/status/1453828900379926528

![FC0JbUYWYAUzvmV](https://user-images.githubusercontent.com/2096101/145730895-735d3f6e-87d6-43ab-888c-86a8f1a580dc.jpeg)

### netlify

![i65asDPK](https://user-images.githubusercontent.com/2096101/145730909-2e7f22c6-5037-4e83-81b0-52c64f864f81.png)

https://twitter.com/Netlify/status/1460684203184558080

### accesiblity

![download](https://user-images.githubusercontent.com/2096101/145730976-55ea924a-c5ca-4b81-8aec-86d77759e02b.png)

https://www.apple.com/accessibility/

**Comment by breadadams** [comment]
### Just JavaScript

![image](https://user-images.githubusercontent.com/5795227/149427435-f396a036-54a4-4ade-bc20-df3caf5162a8.png)

https://justjavascript.com/
