### ISSUE TITLE
select the value under edit

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/cards#23]
`cmd+click` makes possible edit query variables quickly.

However, you need to select value _before_ overwritten it

**current**

<img width="394" alt="Screenshot 2020-04-16 at 23 29 07" src="https://user-images.githubusercontent.com/2096101/79508594-1f4fbf80-803a-11ea-905d-8379e975bd16.png">

**expected**

<img width="401" alt="Screenshot 2020-04-16 at 23 29 33" src="https://user-images.githubusercontent.com/2096101/79508618-28d92780-803a-11ea-887d-57e3dbeae54a.png">

**Comment by jletey** [comment]
I can work on this is no-one else is :)

**Comment by Kikobeats** [comment]
@jletey I totally miss your message! are you still available for doing that? 🙂
