### ISSUE TITLE
Logo not appearing

### ISSUE THREAD

**Issue by CHEWX** [microlinkhq/cards#64]
Hi, 

First of all, great product!

Having issue with a logo not appearing, it works fine in the editor, but the embed code supplied doesn't show the same results.

https://www.treaclewp.com/blog/who-what-where-when-why/

Thanks,
Tom

**Comment by Kikobeats** [comment]
Thanks for reporting @CHEWX, I'm taking a look to understand what's happening 🙂

**Comment by Kikobeats** [comment]
finally found the thing and now the logo is being rendered properly:

https://api.microlink.io/?adblock=false&meta=false&screenshot&element=%23screenshot&embed=screenshot.url&url=https%3A%2F%2Fcards.microlink.io%2F%3Fbg%3D%2523f1f1f1%26domain%3Dtreaclewp.com%2520%25E2%2580%2594%2520Headless%2520WordPress%2520Hosting%26title%3DWho%253B%2520What%253B%2520Where%253B%2520When%253B%2520Why.%26logo%3Dhttps%253A%252F%252Fwww.treaclewp.com%252Flogo-mark.svg%26color%3D%2523010101

🎉

**Comment by CHEWX** [comment]
Oh cool!

Was this an issue at my end? @Kikobeats

**Comment by Kikobeats** [comment]
It was a thing related to Microlink API.

From now, new screenshots should be shown the logo properly and old screenshot have a TTL of 1h by default; after that, we will be regenerated, so you don't need to do anything additional 🙂
