### ISSUE TITLE
Custom image key not displaying on social share images

### ISSUE THREAD

**Issue by phunkren** [microlinkhq/cards#92]
# Preset: ajames

### Editor
https://cards.microlink.io/editor?preset=ajames&title=Adding%20state%20to%20Storybook%20in%20React&subtitle=June%2029%2C%202019%20%7C%203%20min%20read&image=https%3A%2F%2Fstaging.ajames.dev%2Fstorybook.jpg

### Generated URL (source code)
https://i.microlink.io/https%3A%2F%2Fcards.microlink.io%2F%3Fpreset%3Dajames%26title%3DAdding%20state%20to%20Storybook%20in%20React%26subtitle%3DJune%2029%2C%202019%20%7C%203%20min%20read%26image%3Dhttps%3A%2F%2Fstaging.ajames.dev%2Fstorybook.jpg 

## Expected behaviour

- The custom keys should override the preset defaults and display them on the generated micro card image.

## Current behaviour

The micro card displays the title, subtitle **and** the custom image:

- using the microlink card editor
- visiting the [source code](https://github.com/phunkren/ajames.dev/blob/micro-img-bug/src/components/SEO.js#L45)'s [generated url](https://github.com/phunkren/ajames.dev/blob/micro-img-bug/src/utils/generateMicroCardUrl.js#L16) 
- requested in markdown

![Generated by https://cards.microlink.io](https://i.microlink.io/https%3A%2F%2Fcards.microlink.io%2F%3Fpreset%3Dajames%26title%3DAdding%20state%20to%20Storybook%20in%20React%26subtitle%3DJune%2029%2C%202019%20%7C%203%20min%20read%26image%3Dhttps%3A%2F%2Fstaging.ajames.dev%2Fstorybook.jpg)

The micro card displays the title and subtitle but **does not** display the custom or default image:

- sharing on social networks (e.g. https://5f315e57baff020007313c70--ajames.netlify.app/blog/2019-11-07-building-a-responsive-camera-component-with-react-hooks)

![twitter card validator](https://i.imgur.com/7iySadd.png)

**Comment by phunkren** [comment]
@Kikobeats

I've created a short write-up on my findings on the fork:
https://github.com/phunkren/cards/wiki/Image-not-showing-on-share

 Let me know if you think the problem is on your end or mine 🙏

**Comment by Kikobeats** [comment]
@phunkren  is this still a thing? to my eyes, your last PR solves the problem

**Comment by phunkren** [comment]
@Kikobeats yep, sadly still a problem. 

This was logged after the merge

**Comment by phunkren** [comment]
I'm going to close this out, since I'm happy with the default for now ☺️

I've made a note of the issue in https://github.com/phunkren/cards/wiki/Image-not-showing-on-share fro reference if we end up coming back to it 👍

**Comment by phunkren** [comment]
@Kikobeats it looks like it could have been a caching issue. 

Out of interest, is there any way to clear the cache for my preset?

**Comment by Kikobeats** [comment]
yes, passing &force to microlink api request!

https://microlink.io/docs/api/parameters/force
